[build]
  command = "npm run build"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefer-offline"
    [[plugins]]
  package = "netlify-plugin-cache"

  [plugins.inputs]
    paths = [
      "node_modules",
      ".cache"
    ]
